id: ACA4CF9BA
title: 'The Single Oceanic Wisdom: An Aspiration to Recognise the Bardos'
type: translation
pechas:
- I34F00E44
- I2F4F5AF2
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:40:28.952747
  last_modified_at: 2023-01-04 12:40:28.952766
  collections:
  - Jigme Lingpa Series
  - Works of Tibetan Masters
alignment_to_base:
  I34F00E44/8199: D8DD
  I2F4F5AF2/8046: D8DD
